name: learn-env-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pip
  - keras=2.9.0
  - nltk=3.6.7
  - regex=2022.7.25
  - tensorflow=2.9.1
  - xgboost=1.6.1
  - python=3.8
  - numpy
  - jupyter
  - pillow
  - pydot
  - h5py
  - statsmodels
  - missingno
  - pip:
      - sklearn
      - xgboost  
